name: PR Check

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies and build packages
        run: |
          npm install
          npm run link:packages
          npm run build:packages
      - name: Lint and Test
        run: |
          npm run lint:packages
          npm run test:packages
